name: chocolatine

env:
   MIRROR_URL: "git@github.com:TristanGrsge/chocolatine.git"
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"
      
jobs:
  check_repository_cleanliness:
    name: "Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: check_repository_cleanliness
        run: |
          INCORECT_FILES=$(find . -type f -not -path "./.git/*" -wholename "*tmp/*" -or -iname "*pain_au_chocolat*" -or -name "*~" -or -name "#*#" -or -name "*.o" -or -name "*.a" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov")
          for FILES in $INCORECT_FILES; do
            echo "::error file=${FILES#./},title=Unwanted file detected::${FILES#./}"
          done
          if [[ -n $INCORECT_FILES ]]
          then
            exit 1
          else
            echo No unwanted files detected
          fi
  
  check_program_compilation:
    needs: [check_repository_cleanliness]
    name: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: action/checkout@v3
      - id: check_program_compilation
        timeout-minutes: 2
        run: |
         make && make re && make clean && make fclean
   
  run_test:
   needs: [check_program_compilation]
   name: "Run test job"
   runs-on: ubuntu-latest
   container:
      image: epitechcontent/epitest-docker:latest
   steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: make tests_run
        timeout-minutes: 2
        
  push_to_mirror:
    name: "Push to mirror repository"
    needs: [run_test]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
             ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
